//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VRAR : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Button1
        {
            get
            {
                return SteamVR_Actions.vRAR_Button1;
            }
        }
        
        public virtual SteamVR_Action_Boolean Button2
        {
            get
            {
                return SteamVR_Actions.vRAR_Button2;
            }
        }
        
        public virtual SteamVR_Action_Boolean Button3
        {
            get
            {
                return SteamVR_Actions.vRAR_Button3;
            }
        }
        
        public virtual SteamVR_Action_Boolean Button4
        {
            get
            {
                return SteamVR_Actions.vRAR_Button4;
            }
        }
    }
}
